### ISSUE TITLE
Install files in CMakeLists.txt

### ISSUE THREAD

**Issue by tony2guo** [MoffKalast/vizanti#36]
Some files are not installed.
Should install all Python scripts, public folder, and launch files.
The server.py is using ../public folder, so its install destination would need to consider this.

Thank you!

**Comment by MoffKalast** [comment]
For ROS 1 or 2?

I think it should be mostly covered on ROS 2 since colcon build doesn't want to symlink by default, but on noetic I haven't looked into it yet. It's a prerequisite for doing the apt install ros-noetic-vizanti pipeline so I'm getting around to it but it's somewhat lower priority. 

If you can figure out what needs to be changed and where, that would be much appreciated :smile:

**Comment by tony2guo** [comment]
I am using ROS 1 Noetic. I'll try to fix this and create a PR.
