### ISSUE TITLE
Costmap rendering

### ISSUE THREAD

**Issue by v-kiniv** [MoffKalast/vizanti#65]
Continuation of the discussion started [here](https://github.com/v-kiniv/rws/issues/17#issuecomment-1979565886). 
Short description: cost map rendering is broken and not consistent when using RWS or Rosbridge. Coloured costmap renders ok when using RWS but not ok when using Rosbridge, and vice versa.

Top image - RWS, bottom - Rosbridge:
<details>
<summary>Chrome 122.0.6261.94 (Mac), Non-Coloured</summary>
<img width="404" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/88d3bd83-e151-4ea1-8a80-b86e6c8fdfad">

<img width="403" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/4eaa3fee-64b1-4f22-a202-ef65420db199">
</details>

<details>
<summary>Firefox 123.0 (Ubuntu), Non-Coloured</summary>

<img width="539" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/34049958-4cb2-416b-8917-e0e1925b79c0">

<img width="540" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/99f98cdf-5b3e-494d-93fa-eb101d762827">

</details>

<details>
<summary>Firefox 123.0 (Ubuntu), Coloured</summary>

<img width="541" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/46a02e5d-b375-4141-91a9-c220a5edcdf9">

<img width="542" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/022c0070-1cdb-4050-a119-ad1a781e8068">

</details>

Here is the bag I've recorded, I tried to strip non-relevant topics and keep it short to decrease size. I noticed that the robot model is stuck when playing from the bag, but it's consistent between RWS and Rosbridge.

[Download  rec.bag.7z from Google Drive](https://drive.google.com/file/d/1Fw-1N7x2Q4bVLbCFUXY83c1Nbhn-kleo/view?usp=share_link) (123 MB, too large for Github attachment)

**Comment by MoffKalast** [comment]
Thanks for the bag data. Unfortunately I wasn't able to reproduce the issue with it, nor with any of my bags I've looked at. I'm really puzzled as to why, but it seems that whatever the bag publisher does fixes this somehow. I did however manage to reproduce it on a live robot:

Rws:
![image](https://github.com/MoffKalast/vizanti/assets/9977799/7b1a3483-346b-4d85-b3ce-b884686b8237)

Rosbridge:
![image](https://github.com/MoffKalast/vizanti/assets/9977799/cd2c1ebc-b5c6-4edb-bfb8-9dec5bfed61c)

Rviz:
![image](https://github.com/MoffKalast/vizanti/assets/9977799/e87dded2-e055-4175-97dc-82f1a1c9d818)

Looking at [the diffs of both received message objects](https://www.diffchecker.com/0MvEGrm3/) it seems that what's encoded as -1 by rosbridge is instead sent as 255 by rws. I have a feeling there's an unintended signed vs unsigned byte conversion in there somewhere.

I've tested both with cbor compression and without and it doesn't seem to make any difference, so I'm while I'm not sure what the core issue is, I can accommodate those values when processing and seems to render as it should now. 

I've put up a fix to [#66](https://github.com/MoffKalast/vizanti/pull/66) if you can test it out. Might be worth looking into why this happens on the rws side at some point.

**Comment by v-kiniv** [comment]
> I have a feeling there's an unintended signed vs unsigned byte conversion in there somewhere.

Yep, you were spot on. `int8` was treated as `char`. Fixed in https://github.com/v-kiniv/rws/pull/21, now Vizanti map(Non-Coloured) behaves the same on RWS and Rosbridge.
However, now both RWS and Rosbridge have broken "Coloured Costmap":

<img width="405" alt="image" src="https://github.com/MoffKalast/vizanti/assets/1661016/179ff7f8-79dd-4e5b-b30e-28fb2c10bbc3">

**Comment by MoffKalast** [comment]
> Yep, you were spot on. int8 was treated as char. 

Ha neat, it was a bit suspicious that int8 and uint8 in binary map to -1 and 255. If the map values were all in range of 0-127 we'd never even figure out this mismatch since the result would've been the same 😄 

> Yep, you were spot on. int8 was treated as char. Fixed in https://github.com/v-kiniv/rws/pull/21, now Vizanti map(Non-Coloured) behaves the same on RWS and Rosbridge.

Ah good, in that case I suppose we can leave the old setup as-is here since it should be more correct.

> now both RWS and Rosbridge have broken "Coloured Costmap":

I think that's actually working as intended, the problem is that we have two different types of data being sent as OccupancyGrid and only the topic name to tell them apart.

The usual map data is just clear/occupied with values that display as a map, the costmaps however are distance maps that encode the distance is to the nearest obstacle for faster path planning, and they use a different number range. Rendering one as the other is possible, but produces odd results. 

![image](https://github.com/MoffKalast/vizanti/assets/9977799/ff436561-fe0a-4c54-9542-addb4766d506)

Vizanti does automatically switch newly added grid visualizers with "cost" in their topic name to costmap rendering, but that's as far as that detection goes. 

Rviz produces roughly the same result on type mismatch, though it does seem to use a different range and colours all costmap distances black which would be neat to add here too at some point since it looks kinda cool but isn't something that's being used as intended anyway:

![image](https://github.com/MoffKalast/vizanti/assets/9977799/f7757425-41a0-40a2-8374-80a190507183)

**Comment by v-kiniv** [comment]
> Ah good, in that case I suppose we can leave the old setup as-is here since it should be more correct.

Yep

> I think that's actually working as intended, the problem is that we have two different types of data being sent as OccupancyGrid and only the topic name to tell them apart.

OK, so I said it's broken because I checked only on Chrome(Mac), but now I also checked on Firefox and Chromium on Ubuntu 20.04 and there the costmap is rendered ok - bold black borders(non-coloured map) and bold cyan borders(coloured map) on obstacles. 

So it's broken only on Chrome on MacOS:

<img width="400" alt="image" src="https://github.com/MoffKalast/vizanti/assets/1661016/9c0e39d3-4a86-48be-ba4f-5258bad8241d" float="left">

<img width="400" alt="image" src="https://github.com/MoffKalast/vizanti/assets/1661016/674157da-f7b8-4d65-ae41-d867ea70f348">

First I thought maybe it's hidpi related, because it looks like costmap "inflation" around obstacles is not there, but nah, I have 4k resolution and 200% scaling inside Ubuntu VM as well.
Not sure if you intend to support Mac, just wanted to make clear why I thought it's broken.

Another thing that added to the confusion is that you have separate costmap and occupancy, I was expecting that when I enable "Costmap colouring" option I would get occupancy+coloured costmap like Rviz does, but it's a matter of choice of course.

Occupancy+Coloured costmap in Rviz:
<img width="514" alt="image" src="https://github.com/MoffKalast/vizanti/assets/1661016/6aa4c6da-88de-459d-8ebf-c96fc8e70fed">

**Comment by MoffKalast** [comment]
> Chrome on MacOS

Hmm, I mean afaik Firefox and Chromium should behave the same way on MacOS as on other OSes, it's only iOS that forces them to be reskinned Safari.

Based on that picture, the right render looks pixel perfect the same as the one on the left, I don't think that's the costmap topic you're rendering. There tends to be a considerable delay when switching which can be annoying, since the new map needs to be received and processed. I think there shouldn't be much overhead to cache the last received message and reprocess it immediately when the switch is thrown to make it more obvious what's going on.

> Another thing that added to the confusion is that you have separate costmap and occupancy, I was expecting that when I enable "Costmap colouring" option I would get occupancy+coloured costmap like Rviz does, but it's a matter of choice of course.

Ah yes it is a bit more low level indeed, rviz has some plugins that group and autodetect the correct setup. Physically though they are completely separate topics and the base Map renderer in rviz works practically the same way: single topic, single display mode. It would be a good idea to rename "Costmap rendering" to "Colour scheme" for familiarity and have it be a dropdown with raw mode as a debug option too, then it'll be completely identical UI-wise.

For your bag setup you'd need the following separate visualizers to reproduce the usual slam_toolbox plugin setup:
- `/map` topic, costmap rendering disabled
- `/global_costmap/costmap` topic, costmap rendering enabled
- `/local_costmap/costmap` topic, costmap rendering enabled, higher opacity

It might be good to add some more heuristics for this detection (e.g. slam_toolbox widget that merges all three + service proxy buttons for its API), but not every slam stack has the same name convention and I wouldn't want to favor one over another too much in principle to not contribute towards vendor lock-in. E.g. back on Noetic there is an alternate slam package `iris_lama_ros ` which has `/distance` as the costmap topic for example.

> Not sure if you intend to support Mac, just wanted to make clear why I thought it's broken.

Well there has been some effort put into Safari compatibility since that's the only option on iOS (e.g. no fetch or xhr requests are used because Apple's ATS blocks them over HTTP and you can't use HTTPS offline without an imported root cert which is a major hassle to set up), but I currently don't have any devices capable of running Safari to test on, nor is it possible to VM it, so it's mostly up to those that use it to help with compatibility fixes for the time being.

**Comment by MoffKalast** [comment]
There, I've extracted the colour mappings from rviz so rendering should now be almost identical, with a little more transparency for unoccupied pixels which looks nicer imo. Also added raw mode as it serves as an impromptu dark mode for maps and caching for instant switching. Should be less confusing now I hope 😄 

Can be tested as part of #68

**Comment by v-kiniv** [comment]
> Based on that picture, the right render looks pixel perfect the same as the one on the left, I don't think that's the costmap topic you're rendering.

You're right, I didn't notice that in Chrome on Mac the Topic option was set to `/map` instead of `/global_costmap/costmap`. When I set the correct topic it works the same way as on Ubuntu, sorry for the confusion. 

> Can be tested as part of https://github.com/MoffKalast/vizanti/pull/68

Not sure, but I think you have typo [here](https://github.com/MoffKalast/vizanti/pull/68/files#diff-2ceb0edad2f2009f133ee2054b6a88329dd1d76e2725ea53219628728bc439d2R30) and [here](https://github.com/MoffKalast/vizanti/pull/68/files#diff-2ceb0edad2f2009f133ee2054b6a88329dd1d76e2725ea53219628728bc439d2R33) and meant to set alpha value to non-zero value, because right now it looks like this:
<img width="562" alt="image" src="https://github.com/MoffKalast/vizanti/assets/1661016/b3bc0c71-798d-4b9d-a99b-9cfcf7217d6a">

And if you'd set alpha to something like 128
```js
let color = [0, 255, 0, 128]; // Green for illegal positive values
// ...
color = [0, 0, 0, 128]; // Black for value 0
```
the result would be:
<img width="562" alt="image" src="https://github.com/MoffKalast/vizanti/assets/1661016/97defbcc-ef25-4645-b7b4-ec6e2fd8cc4a">

Anyway, new rendering style looks much better, maybe it's because I used to Rviz.

**Comment by MoffKalast** [comment]
Yeah I'm still not sure about that alpha value here, but it shows up a bit weird in some cases if it's high enough, since the costmaps stack and [it does seem to really be zero in rviz2](https://github.com/ros2/rviz/blob/f2fa3e764335583380ae8fb1c7412b493c175ff9/rviz_default_plugins/src/rviz_default_plugins/displays/map/palette_builder.cpp#L121):

![image](https://github.com/MoffKalast/vizanti/assets/9977799/994ca2d8-9de7-4886-a163-cd004a1ea3a1)

I think it makes most sense to keep the original three options as close to rviz as possible, but thing is though... it would be pretty easy to just add a few extra new ones if you have any specific colour schemes you'd like to see. One that might be interesting is walls-only, which would be the original broken version that only shows hard obstacles.

**Comment by v-kiniv** [comment]
So, my intention was to get something like this:
<img height="500" alt="image" src="https://github.com/MoffKalast/vizanti/assets/1661016/ff2ea14d-081b-41f2-addb-1cc274d485cd">

Basically, occupancy, local and global costmap combined. But it's a separate layers in Vizanti, and my tweak with non-zero alpha produced kinda combined layer, but it's more like a side effect than a proper solution.

I think we can close the issue, as discrepancy in map render between RWS and Rosbridge was fixed and the "broken costmap" was just wrong widget settings on my end.
