### ISSUE TITLE
Add ros camera images

### ISSUE THREAD

**Issue by Bhanu5302** [MoffKalast/vizanti#8]
Please enhance the code to display the camera images on web view

**Comment by MoffKalast** [comment]
I've been thinking about this problem yeah, and it's an annoying one for sure because it's filled with tradeoffs. The standard way images are sent through rosbridge is by encoding them as base64, making them about 30% larger which completely clogs web tcp sockets at any reasonable rate. Could work with heavy throttling I suppose, but even transferring OccupancyGrid type images freezes other topics for a split second.

Second option is the web_video_server, with mjpeg streaming which is workable over wifi at low resolutions and low frame rates and goes through http requests so it doesn't directly impact socket transfers (probably the most sane option).  webrtc_ros used to be a better option, but building webrtc is such an undertaking that it hasn't been kept up to date at all. I think another option would be using aiortc through python, since they handle that part but one would need to build a web_video_server type node around it.

As for displaying the images client side, it's also not ideal since there's very little screen real estate on mobile. Could work on desktop with a movable scalable pop-out window, but if a camera position is defined in the TF tree then maybe something like [a floor reprojection that assumes the floor is at Z=0](https://www.a1k0n.net/2021/01/22/indoor-localization.html) (scroll all the way down) would be more practical, though if there's no localization it would only be fixed in the camera frame and if the camera isn't seeing any of the floor then it's not useful either. 

So no silver bullets unfortunately, but I'd like to hear what everyone thinks.

**Comment by MoffKalast** [comment]
Alright I've ran some tests and surprisingly the compressed image doesn't seem to be too bad (if throttled somewhat and this is at roughly 400x300 px), so I suppose it may be handy to have it until someone figures out aiortc. It'll be a with similar drag setup interface as for the joystick for now.

![image](https://github.com/MoffKalast/vizanti/assets/9977799/271e6aad-593f-4ae5-ad6b-0c1cc17c5098)
